### ISSUE TITLE
Copy Thunderstore `manifest.json` into corresponding nsmod directory

### ISSUE THREAD

**Issue by GeckoEidechse** [AnActualEmerald/thermite#1]
In order to see which Thunderstore mod a Northstar mod belongs to some mapping needs to be established.

The approach [Viper](https://github.com/0neGal/viper/) took is simply copying over the Thunderstore `manifest,json` into all the Northstar mod folders that belong to said Thunderstore mod.

[FlightCore](https://github.com/R2NorthstarTools/FlightCore/) currently copies the Thunderstore mod string into the mods' `mod.json` which also allows for a mapping but (a) interferes with the mods' files and (b) contains less information then the `manifest.json`.

As such copying the `manifest.json` is the more elegant solution. Further this allows interoperability between mod-managers (at least Viper and with this change papa and FlightCore). Could talk to Juicy to follow suit in VTOL ^^

The main thing to watch out for is that a Thunderstore mod can contain multiple Northstar mods. As such, one needs to take care to copy the `manifest.json` to all of them ^^

**Comment by AnActualEmerald** [comment]
This should be working now as of `0.4.0-rc.1` :+1:
